name: Deploy to Okteto

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest' # Puedes ajustar la versión según tus necesidades
          installKubectl: true

      - name: Set up Okteto CLI
        run: |
          curl https://get.okteto.com -sSfL | sh
          sudo mv okteto /usr/local/bin

      - name: Okteto login
        run: okteto login --token ${{ secrets.OKTETO_TOKEN }}

      - name: Deploy to Okteto
        run: |
          kubectl apply -f k8s/deployment.yaml
